/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testTamanhoDoVetor() {
        Vetor vetor = new Vetor();
        // [0,0,0,0,0]
        // [1,2,0,0,0]
        assertEquals(0, vetor.getTamanho());
    }

    @Test
    public void testAdicionarUmElemento() {
        Vetor vetor = new Vetor();
        vetor.adicionar(1);
        assertEquals(1, vetor.getTamanho());
    }

    @Test
    public void testAdicionarDezElementos() {
        Vetor vetor = new Vetor();
        for (int i = 0; i < 10; i++) {
            vetor.adicionar(i);
        }
        assertEquals(10, vetor.getTamanho());
    }
}
