/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

public class App {

    public static void main(String[] args) {
        Vetor vetor = new Vetor();

        long timeNow = System.currentTimeMillis();
        System.out.println(timeNow);

        for (int i = 0; i < 10; i++) {
            vetor.adicionar(i);
        }

        long after = System.currentTimeMillis();
        System.out.println(after);
    }
}
